### ISSUE TITLE
License file.

### ISSUE THREAD

**Issue by stark1tty** [nathanlesage/academics-on-mastodon#119]
Hey, I'm on mobile but a quick check on this and I didn't see a license file. May want to include one. :)

**Comment by nathanlesage** [comment]
I'm not sure this list can be really licensed? The only I could think about would be a CC. Your thoughts?

**Comment by stark1tty** [comment]
I think that's just fine. :)

**Comment by trutzig89182** [comment]
For the header image the image of the mastodon mascot is licensed as copyleft to my knowledge. I don’t claim any copyright to the rest and it can be used any way people want. But perhaps linking to this paragraph in my repository could be helpful, so that people know how to use and adapt it: https://github.com/trutzig89182/Mastodon-Sociologists#create-your-own-preview-image-for-the-page

For the license for the page: Perhaps it would be good to make sufficiently clear that the license does not count for the content of the individual lists? This could be a bit confusing for a user who is not familiar with the structure, especially if there is a similar styling which can foster the impression that the pages are somehow managed together.

**Comment by nathanlesage** [comment]
Sounds good. I'll adapt and do so tomorrow. Thank you for your input.
