### ISSUE TITLE
Reporting some broken links

### ISSUE THREAD

**Issue by sumitchakravarty** [nathanlesage/academics-on-mastodon#143]
Thanks for the list.  I noticed a few broken links on the readme and ran a link checker, here are the results (in case you know the new addresses).

| Status	| URL	| Source link text |
| ------------ | ---------- | -------- |
| 404 Not Found	| https://github.com/nathanlesage/academics-on-mastodon/tree/{{ urlEncodedRefName }}	| {{ refName }} default| 
| 404 Not Found	| https://sidhuk.github.io/Mastodon-TeamMassSpec/	| Mass Spec| 
| -1 Not found: An error occurred in the secure channel support	| https://social.edu.nl/@Bibliothecaris	| @Bibliothecaris@social.edu.nl | 
| -1 Not found: The host name in the certificate is invalid or does not match	| https://atmoschem.org/explore	| Atmoschem | 
| -1 Not found: A connection with the server could not be established	| https://med-mammoth.com/	| Med-Mammoth | 
| 500 Internal Server Error	| https://qubit-social.xyz/about	| Qubit | 
| 502 Bad Gateway	| https://science.social/	| science.social
| -1 Not found: A connection with the server could not be established	| https://lem.clinicians-exchange.org/	| Clinicians Exchange | 
| 404 Not Found	| https://github.com/search/feedback	| form/action(post) |

**Comment by nathanlesage** [comment]
Thanks I guess for the two true positive results in that table. Next time, I expect you to take a look at the results of whatever tool you've been using to see that the link "github.com/search/feedback" for example is not part of the actual Readme file, and double-check the other links to see that apparently that tool was incapable of properly visiting those domains, since a few of those were working.

I'm happy to take feedback, but not this type of low-effort issues.
