### ISSUE TITLE
RGPD : ask (and validate) user to be on list ?

### ISSUE THREAD

**Issue by Shnoulle** [nathanlesage/academics-on-mastodon#84]
I see a lot of list,
I know you reference only list of list and not directly the people on the list.
I know the list are cool and great to be used , but : it's not the way to do !

I see there are way to be removed from list. But how somebody can know is on the list ?

The only better way to allow such list is to have a clear OptIn ! With a **validation** on the user account on mastodon.

PS : all forms seems to be on google … then : have a relation between google account and mastodon account … it's worts than i think …

**Comment by stark1tty** [comment]
People voluntarily add themselves to the lists and remove themselves via methods deemed by the list owner. They are managed by different people within the different disciplines. This is just a meta collection of different lists that are floating around and are not controlled by this GitHub. All lists have been added with the list manager's permission.

**Comment by Shnoulle** [comment]
> People voluntarily add themselves

How the validation are done ? How you confirm the current user are really the mastodon user and twitter user ?

And more : I can create an account on any mastodon server and tell you i'm "Doctor Name" …

> This is just a meta collection of different lists

Yourself manage a lot of list, 

>  All lists have been added with the list manager's permission.

I don't care about List Manager …

**Comment by stark1tty** [comment]
I only manage one list. I contribute to this meta-list of lists as well. Validations are not done because these are not meant for any official purposes, rather their purpose is to reconnect academics as they move to Mastodon from Twitter and reconnect their networks. They are organic tools run by voluenteers and not official documents. It is likely that issues with users on the lists are dealt with by the individual list managers on a case-by-case basis.

**Comment by nathanlesage** [comment]
Okay, there seems to be a lot to unpack here. Of course there is a tradeoff between privacy/security and ease of use. But I am convinced that the solution we came up with collectively is well balanced in all those respects. @stark1tty already said everything there can be said regarding the role these lists fulfill, so thank you for jumping in here!

Now, I do not think you meant it to come across as such, but statements such as "I don't care about list managers" or "That's not the way to do it" come across as very rude. Especially the list managers carve out a portion of their free time every day to maintain those lists, adding new accounts and removing others. And the whole scientific community benefits from that. Those people who are on those lists are obviously fine with the ways and means the list maintainers give them to add and remove themselves, otherwise they would have opted not to be part of those lists.

I have had a look at every single list that is collected here in this repository and verified that it meets the collective expectations. And thus far, nobody has issued any concerns regarding potential privacy issues or impersonation. Should these occur at any time, the list managers themselves are pretty responsive, and if they don't, one can contact me so that I can take action from here as well. So there are sufficient safeguards in place to ensure everybody plays by the rules.

If you would like me to address the various concerns you have raised individually, I can do so, but please try to remember that everything the people here do is voluntarily when you formulate a response. Until then, I consider this issue as answered.

**Comment by stark1tty** [comment]
You have done a good job getting everyone together. Thanks for your hard work. It is a valuable resource as we depend on social media so much these days.
