### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by stark1tty** [nathanlesage/academics-on-mastodon#88]
User: @mastodonmigration@mastodon.online is duplicating lists without permission. I put a report though, but I am not sure what to do about this. It's a privacy concern as they are not linked to the organic original documents. 

![2022-11-23 19_38_31-](https://user-images.githubusercontent.com/69326376/203632818-a2801158-8d5f-4323-b8b4-13ed9e664325.png)

**Comment by stark1tty** [comment]
This user is also feigning ignorance when multiple list owners are pointing out that this is not OK.

**Comment by nathanlesage** [comment]
Oy, that sounds nasty o.O

So I mean it was absolutely right of the list owners to reject that idea, since they're the responsible people for that, and it seems that they've stopped the duplication of lists, so yes, it looks resolved.

I think in general it is good to open such issues here on the "main" list, simply because it's a central place, so other people will be more likely to see this. So please, if you (or anyone else reading this) notice something like that, please feel free to continue opening issues here.

These issues can then also serve to coordinate between the list maintainers!
